name: Deploy Infrastructure

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (e.g. dev, prod)'
        required: true
        default: 'dev'
      # terraform_action:
      #   description: 'Terraform Action'
      #   required: true
      #   default: 'apply'
      #   type: choice
      #   options:
      #   - apply
      #   - plan

permissions:
  contents: read
  id-token: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_USE_OIDC: true
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  # Variable for the role assignment target - Make sure TARGET_PRINCIPAL_ID is added to GitHub Secrets
  TF_VAR_target_principal_id: ${{ secrets.TARGET_PRINCIPAL_ID }}

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v3

    # - name: Terraform Init
    #   run: terraform init

    # - name: Terraform Plan
    #   run: terraform plan -input=false

    # - name: Terraform Apply
    #   if: inputs.terraform_action == 'apply'
    #   run: terraform apply -auto-approve -input=false

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Store Secrets in Key Vault
      # if: inputs.terraform_action == 'apply'
      run: |
        KV_NAME="kv-meghank-riskinsure"
        
        az keyvault secret set --vault-name "$KV_NAME" \
          --name "CosmosDbConnectionString" --value "test connection stringhellop" || echo "⚠️ Key Vault not ready"
        
        az keyvault secret set --vault-name "$KV_NAME" \
          --name "ServiceBusConnectionString" --value "test service bus connection string" || echo "⚠️ Key Vault not ready"

    
    